# Generated by Django 5.0.7 on 2024-08-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="default-slug"),
        ),
    ]
