# Generated by Django 5.0.7 on 2024-08-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postsApp", "0002_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(),
        ),
    ]
